### ISSUE TITLE
[2.4.2] Machines don't process correctly

### ISSUE THREAD

**Issue by beans-squared** [TeamAOF/All-of-Fabric-3#195]
Hello, I'm running a AOF server with a few friends and have noticed some strange behavior with processing machines from Industrial Revolution and Tech Reborn. A few issues we found: For every third item processed, the machine would give no output item. The machine would refuse to operate past one item in the output slot. Items would refuse to stack past a stacksize of one.

Let me know if you need logs or any other info. Hoping for a fix soon! Great pack <3

**Comment by beans-squared** [comment]
I'm taking a wild guess here but it might have something to do with Inventory Sorting. Its latest version only supports 1.16.3.

**Comment by dandin87** [comment]
From 1.16.2-1.16.4 there were not any breaking changes to the minecraft mappings. This means that all 1.16.2 mods work on .3 and .4 and same for the other way around. The only reason they would not is if the Mod Dev sets a requirement to only run in a specific version, in which case Minecraft would not boot and it would tell you which mod. The developer would only need to change 1 line to fix that. Just because the curseforge page for the mod has not been updated to reflect it still working does not mean it does not work.

Now the stacking issue is known, and the 2.4.2 Release was changed to alpha. We are still trying to track that one down. Its safe to say its not Inventory sorting because this bug was introduced by one of the mods that were updated.

**Comment by beans-squared** [comment]
Gotcha.

**Comment by turtledev1** [comment]
Duplicate of https://github.com/TeamAOF/All-of-Fabric-3/issues/194

**Comment by beans-squared** [comment]
Fixed in latest release.
