### ISSUE TITLE
Applied energistics 2 bug

### ISSUE THREAD

**Issue by jppmcosta** [TeamAOF/All-of-Fabric-3#264]
I inserted one of my backpacks from Inmis inside the system of applied energistics and when I try to take it out I get the Connection Lost message. Another item that i can't take from the system is the Space Suit Chest from Astromine, but this one doesnt disconnect me.
Another question that I have is how do I swap wings from the Winged Mod?

**Comment by k3nw4y** [comment]
about the winged mod, you have to rightclick with the daggere to remove the wings,then you can craft a new wing with the same broken core of flight, iirc you can remove the astromine items with an export bus and fuzzy card

**Comment by Monster-Zer0** [comment]
Please let Ae2 know about the Ae2 bug.

**Comment by Technici4n** [comment]
I am pretty sure the root issue comes from use of Cardinal Components on items. Not much can be done about this on AE2's side, the solution is simply not to use CCA items...

- Extract these items from AE2 using export bus + fuzzy card.
- Don't put them in the ME system afterwards.
- Open an issue on the mod so that they stop using CCA for items.
