### ISSUE TITLE
gray dye - empty recipe

### ISSUE THREAD

**Issue by MSandro** [TeamAOF/All-of-Fabric-3#278]
![image](https://user-images.githubusercontent.com/10937159/106873836-2af99900-66d5-11eb-9542-0c7c4b38b4ca.png)
![image](https://user-images.githubusercontent.com/10937159/106873902-3e0c6900-66d5-11eb-9df1-782f9678446a.png)
There is an empty recipe for gray dye. Not sure which mod is causing this, but it is realy annoying in the ME System Crafting Terminal.

**Comment by SlendyMan0** [comment]
I can verify that it's still an issue. 
![2021-05-10_17 09 10](https://user-images.githubusercontent.com/18384284/117681855-cf96e580-b1b2-11eb-856a-d1add89f45aa.png)

**Comment by dandin87** [comment]
Fixed in pack v2.8
BYG creates a byg:gray_dye tag that has nothing in it, aka null
it then creates a recipe for minecraft:gray_dye using tag byg:gray_dye to make it, since the tag byg:gray_dye is null the recipe is nothing in the crafting grid to produce gray dye.
 https://github.com/TeamAOF/All-of-Fabric-3/commit/bde56580c17acc6c9b14049f6da61a9b3b241847
