### ISSUE TITLE
Using Sodium causes some item and block textures to not load properly

### ISSUE THREAD

**Issue by manicogaming** [TeamAOF/All-of-Fabric-3#313]
I know Sodium is not part of the modpack but is there anyway that you could make Sodium compatible with the ModPack without any errors?

Here's a screenshot of the problem:

[https://imgur.com/a/HQK2CLE](url)

**Comment by dandin87** [comment]
If you had gone to the #faqs channel in our Discord server, you would have seen you need Indium. You also need the Sodium Next branch, and not what is on curseforge. Will be updating the post in #faqs to link to Github Build Artifacts instead of providing a download. You will want to extract the files from the build-artifacts.zip both zips will have the same name, but of course contain different mods. You want just 1 jar file from each zip. indium-1.0.0.jar and sodium-fabric-mc1.16.4-0.1.1-SNAPSHOT.jar
Below are the downloads. I rename them with the date added at the end so that I know if there has been any new commits since i last downloaded.
https://github.com/comp500/Indium/suites/2191781121/artifacts/45207897
https://github.com/comp500/sodium-fabric/suites/2195121490/artifacts/45292669
