### ISSUE TITLE
New Chunk Crash

### ISSUE THREAD

**Issue by Darc-Kross** [TeamAOF/All-of-Fabric-3#315]
crash message: The game crashed whilst exception generating new chunk
Error: java.lang.IllegalStateException: Unknown biome id emitted by layers: 260
Exit Code: -1
[crash-2021-03-11_15.28.42-server.txt](https://github.com/TeamAOF/All-of-Fabric-3/files/6126110/crash-2021-03-11_15.28.42-server.txt)

**Comment by dandin87** [comment]
In the config folder delete survivalisland.json or edit the startingBiome. Ecotones:Temperate_forest is no longer a biome and this was a very old config that Ak9 was messing with at some point. We will change this back to its default in the next update.
Here is the bad config.
{
  "islandSize": 7,
  "islandRarity": 6,
  "startingBiome": "ecotones:temperate_forest",
  "generateBeaches": true,
  "seperateBiomes": true,
  "hardcoreMode": true
}
This is the default config.
{
  "islandSize": 5,
  "islandRarity": 6,
  "startingBiome": "minecraft:forest",
  "generateBeaches": true,
  "seperateBiomes": true,
  "hardcoreMode": false
}

**Comment by dandin87** [comment]
Just some more info. Player created a world in single player and played for about 5 hours. Crashed happened whenever they went North. I would have expected the game to crash right away since the biome doesn't exist but I suppose it actually started them in a different biome. Either way deleting the config or changing it to default fixed the issue. Leave this open until Ak9 fixes the config

**Comment by Monster-Zer0** [comment]
no response from OP.. closing
