### ISSUE TITLE
Can't eat? 

### ISSUE THREAD

**Issue by FallingLily0515** [TeamAOF/All-of-Fabric-3#331]
Hiya, I'm fairly new to java minecraft (just moved from bedrock) and so I'm really new to using mods etc. Now I don't know if I'm just being stupid, but I'm suffering from Malnutrition, but I can't seem to eat anything? I've made sandwiches, I've cooked meats, all I've manged to consume is honey and a golden apple? Am I doing something wrong? Thanks in advance.

**Comment by kabadesu** [comment]
If you open the nourishment UI through your inventory screen (look for the carrot icon in the top right), I suspect you're full of sweets. You'll have to run around our get hurt to reduce that bar and then pick healthy options for your diet.

**Comment by FallingLily0515** [comment]
> If you open the nourishment UI through your inventory screen (look for the carrot icon in the top right), I suspect you're full of sweets. You'll have to run around or get hurt to reduce that bar and then pick healthy options for your diet.

Unfortunately this is not the case... My sweets Re about 1/4 full?

**Comment by dandin87** [comment]
This is probably not the case, but it sounds like you might have picked something up with carrier by shift right clicking with empty hands? When carrying something you can't interact with anything until you put it down. But you said you've made sandwiches and cooked meat so this is probably not the case. Are you saying it will let you eat golden apples and honey, but you cannot eat steak, pork chop, cooked chicken, or a sandwich? Right clicking with them in your hand is not doing anything? 

How did you install the pack? Curseforge launcher often messes up installing everything correctly, so we recommend GD Launcher or MultiMC. 

Probably doesn't apply here, but if you copied the mods to use in the vanilla launcher you also have to make sure you copy config and kubejs folders otherwise it will break a whole lot of stuff.

**Comment by FallingLily0515** [comment]
> This is probably not the case, but it sounds like you might have picked something up with carrier by shift right clicking with empty hands? When carrying something you can't interact with anything until you put it down. But you said you've made sandwiches and cooked meat so this is probably not the case. Are you saying it will let you eat golden apples and honey, but you cannot eat steak, pork chop, cooked chicken, or a sandwich? Right clicking with them in your hand is not doing anything?
> 
> How did you install the pack? Curseforge launcher often messes up installing everything correctly, so we recommend GD Launcher or MultiMC.
> 
> Probably doesn't apply here, but if you copied the mods to use in the vanilla launcher you also have to make sure you copy config and kubejs folders otherwise it will break a whole lot of stuff.

Yeah, I could eat honey and golden apples but nothing else I tried. It has just fixed itself now. Just did a complete restart. Maybe just glitched temporarily?

Thank you for your advice!

**Comment by kabadesu** [comment]
I had experienced something similar to this when nourishment was first added to the pack, but could never reproduce it so figured I had just done something wrong.
