### ISSUE TITLE
Monsters spawning with big torches down?

### ISSUE THREAD

**Issue by SnugglebunnyX** [TeamAOF/All-of-Fabric-3#347]
Hello! I have AOF 2.7.2 installed and am using a full Big Torch from the Kibe mod to keep monsters from spawning, yet they continue to spawn. Is this an issue or a change in mechanics?

**Comment by Monster-Zer0** [comment]
You put torches in your big torch?

**Comment by dandin87** [comment]
Many of the bewitchment mobs are not using Hostile::CanSpawnInDark. And Kibe Big Torch only prevents mob spawns from mobs that spawn based on low light level.

**Comment by SnugglebunnyX** [comment]
Yeah, I put torches in the big torches and we were having issues with zombies/skellies spawning. Hasn't happened since server reset though so it may have been a glitch.

**Comment by dandin87** [comment]
That is a bug with Phosphor causing some chunks to stop updating their light value, and so the game see 0 light level and will spawn mobs. Starlight is a Light engine replacement mod and fixes that issue. it also performs better than Phosphor. I would delete phosphor form the server mods folder and add Starlight. We have been using starlight on the public servers since December. Clients do not need to switch mods unless they experience the same issue in single player, which is very very rare.
https://github.com/Spottedleaf/Starlight/releases/tag/1.0.0-RC2
