### ISSUE TITLE
[Feature/BUG?] compatible Tech reborn and Industrial revolution cables 

### ISSUE THREAD

**Issue by vanari** [TeamAOF/All-of-Fabric-3#366]
# Tech reborn and Industrial revolution cables are not compatible.
![2021-05-16_23 43 06](https://user-images.githubusercontent.com/36865376/118413657-f6ac5600-b68f-11eb-9662-8902a9f8ed75.png)
![2021-05-16_23 43 16](https://user-images.githubusercontent.com/36865376/118413660-f744ec80-b68f-11eb-9453-0851843ce9fc.png)
# Batteries aswell.
![2021-05-16_23 47 00](https://user-images.githubusercontent.com/36865376/118413724-47bc4a00-b690-11eb-843d-696a7d826ca1.png)

**Comment by dandin87** [comment]
Actually Indarev cables can power TR but TR cannot directly power IndRev. In your second pic with the IndRev Cables and TR cables power is actually being transfered, the textures just do not connect. This is by design as TR's energy API is not very great and is laggy. Eventually I'm sure it will be updated to use what IndRev is using. Until then, IndRev cables can and will work to power both IndRev and TR. Also, you can have TR cables upto 1 block away from IndRev Machines and then have 1 IndRev Cable between the TR cables and the IndRev machine. The textures won't connect between cables but it will transfer energy.
