### ISSUE TITLE
Art of Alchemy Compatibility

### ISSUE THREAD

**Issue by Blazeord** [TeamAOF/All-of-Fabric-3#375]
Should be fairly easy to add recipes for modded items, in particular bewitchment and art of Alchemy would pair nicely together. Currently there's no essentia recipes to use in the synthesiser for most items. Something like bark or a demon horn should definitely have recipes imo. Ideally you'd have recipes for every obtainable item in the game and then you could have your ME system just be a fluid network that crafts every item but this is obviously not gonna happen as it would be too much work.

**Comment by irunatbullets** [comment]
You could create some recipes for this using kubejs. There's some pretty good examples for it here https://gist.github.com/LatvianModder/9f5f8cb4121fda4141dbd2cfd5b3d5c9

AoA is set for removal from the pack in 2.8 due to some performance issues and seemingly inactive development. If the issues are sorted we might see it again sometime, because it is pretty cool.
