### ISSUE TITLE
[BUG] Eye of Ender unable to be thrown and lead to the Stronghold

### ISSUE THREAD

**Issue by MNRainDrop** [TeamAOF/All-of-Fabric-3#407]
**Modpack Version**
Using Modpack Version 2.8.3.

**Describe the bug**
It seems that when trying to use an Eye of Ender, it is not thrown, let alone in the direction of the Stronghold.

**To Reproduce**
1. Get an Eye of Ender
2. Right-click the Eye of Ender
3. Eye of Ender is not thrown
4. See Bug

**Expected behavior**
Normally, the Eye of Ender would be thrown and lead to the Stronghold (vanilla Minecraft feature).

**Comment by TelepathicGrunt** [comment]
Are you using an existing world when you upgraded AOF3? If so, the newest update for RS was a big update and part of the warning to updating to it is:
![image](https://user-images.githubusercontent.com/40846040/121101203-66ae8780-c7c9-11eb-950c-733b918665ac.png)

The reason for me removing the stonebrick stronghold structure from my mod is because I redid my nether stronghold to be a jigsaw structure so I can delete vanilla's cursed stronghold code I borrowed, the stonebrick stronghold wasn't a "repurposed" structure for a new biome or dimension so it doesn't fit in my mod, and Better Strongholds mod exists which does a better job with redoing the vanilla strongholds.
 
You can try manually downgrading RS in your world

**Comment by penbob3** [comment]
With latest AOF3 version (2.8.4) this appears to happen on any new world generated. Both server and client tests I did ended with the Eye of Ender not throwing and the /locate betterstrongholds:stronghold command resulting in 'Could not find that structure nearby'. Seeds 8747260616870253500, -4950647801679167555 and -877952845482585995 given as examples for brand new worlds.

**Comment by TelepathicGrunt** [comment]
@penbob3 can you whitelist all dimensions in better stronghold’s config and try again?

**Comment by penbob3** [comment]
I added all the dimensions I could think of, including Miner's Horizon ('minershorizon:miners_horizon' I believe), and the outcome is the same as before in all dimensions: /locate returns the error and Ender Eyes can't be thrown.
