### ISSUE TITLE
Latest version not in CurseForge or Multimc

### ISSUE THREAD

**Issue by henkaa** [TeamAOF/All-of-Fabric-3#416]
**Is this a modpack or mod issue?**
Modpack question

**Modpack Version**
2.8.5

**Describe the bug**
This is more of a question than a bug. Is 2.8.5 to be added to either CurseForge or Multimc? I can't find it in either, latest is 2.8.4. Or is there a new way to start this sine the new loading mechanim?

**To Reproduce**
- Open Curse
- Try to update to latest version
- Latest is 2.8.4
- Open Multimc
- Try to install (I do not have any version of All of Fabric 3 on my Multimc)
- Latest is 2.8.4

**Expected behavior**
Latest version is 2.8.5

**Comment by dandin87** [comment]
First, multiMC pulls from Curseforge, so of course it's the same there. 
There are issues with how Curseforge refactored things to support Fabric Loader. Currently, We cannot update the pack there as it gets automatically rejected because of mods that have 1 jar for both Fabric and Forge, we have tried to get it manually approved but instead they are making us wait until they fix the issue on their end. There is no eta. We cannot even upload it as a forge/jumploader pack like it previously worked. 
2.8.5 changes are also not final yet. But the only important change is the Better Strongholds config change which fixes strongholds not generating. For now, you can simply download or copy the changes from the 2.8 branch here on girhub.

**Comment by henkaa** [comment]
Well, 2.8.5 has been on CurseForge a while now, so closing this issue :)
